# Goal: 
Scrape the entirety of basic box score data exposed by the SportsReference API.

Here, we import the libraries we need in order to perform data exploration and carpentry on our nba box score data. The Sports Reference package allows us to interact with the data.

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from sportsreference.nba.teams import Teams
from sportsreference.nba.roster import Roster, Player
from sportsreference.nba.boxscore import Boxscore, Boxscores
pd.set_option('display.max_columns', 500)

In [2]:
basic_boxscores = pd.DataFrame()

Here, we are loading boxscores from 1940 to 2019. We are extracting box score data by season (defined as starting in August of a particular year and concludes in July of the next year). Games for a particular day are packed inside the games suffix so we must call games.games in order to unpack the data. We then iterate through each game for each day in the NBA seasons and load the boxscores into the `basic_boxscores` dataframe. 

After populating the dataframe, we then write it to CSV for future usage. 

**The Sports Reference API crashes a lot. We have added in check points to save the Data being loaded in. Comment out sections after completion to ensure data is saved correctly** The first cell is the complete year range. Run this cell first, change the ranges of the following cells based on if the API crashes. The cells under this first cell are the ranges that worked for us, but your usage might vary.

In [4]:
# basic_boxscores = pd.read_csv('../Data/nba_boxscores.csv')

In [ ]:
# for year in range(2019,1945,-1):
#     print(year)
#     games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
#     games_dict = games.games
#     for date, games in games_dict.items():
#         for game in games:
#             cols = game.keys()
#             cols = list(cols)
#             cols.append('season')
#             data = pd.DataFrame(game.values()).transpose()
#             data['season'] = year
#             basic_boxscores = pd.concat([basic_boxscores,data])
#     print(year,' Loaded\n=================')
#     basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

In [3]:
# for year in range(2019,2016,-1):
#     print(year)
#     games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
#     games_dict = games.games
#     for date, games in games_dict.items():
#         for game in games:
#             cols = game.keys()
#             cols = list(cols)
#             cols.append('season')
#             data = pd.DataFrame(game.values()).transpose()
#             data['season'] = year
#             basic_boxscores = pd.concat([basic_boxscores,data])
#     print(year,' Loaded\n=================')
#     basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

In [5]:
# for year in range(2016,2000,-1):
#     print(year)
#     games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
#     games_dict = games.games
#     for date, games in games_dict.items():
#         for game in games:
#             cols = game.keys()
#             cols = list(cols)
#             cols.append('season')
#             data = pd.DataFrame(game.values()).transpose()
#             data['season'] = year
#             basic_boxscores = pd.concat([basic_boxscores,data])
#     print(year,' Loaded\n=================')
#     basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

In [6]:
# for year in range(2000,1900,-1):
#     print(year)
#     games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
#     games_dict = games.games
#     for date, games in games_dict.items():
#         for game in games:
#             cols = game.keys()
#             cols = list(cols)
#             cols.append('season')
#             data = pd.DataFrame(game.values()).transpose()
#             data['season'] = year
#             basic_boxscores = pd.concat([basic_boxscores,data])
#     print(year,' Loaded\n=================')
#     basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

In [8]:
# for year in range(1997,1900,-1):
#     print(year)
#     games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
#     games_dict = games.games
#     for date, games in games_dict.items():
#         for game in games:
#             cols = game.keys()
#             cols = list(cols)
#             cols.append('season')
#             data = pd.DataFrame(game.values()).transpose()
#             data['season'] = year
#             basic_boxscores = pd.concat([basic_boxscores,data])
#     print(year,' Loaded\n=================')
#     basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

In [10]:
for year in range(1982,1945,-1):
    print(year)
    games = Boxscores(datetime(year-1,8,1),datetime(year,7,30))
    games_dict = games.games
    for date, games in games_dict.items():
        for game in games:
            cols = game.keys()
            cols = list(cols)
            cols.append('season')
            data = pd.DataFrame(game.values()).transpose()
            data['season'] = year
            basic_boxscores = pd.concat([basic_boxscores,data])
    print(year,' Loaded\n=================')
    basic_boxscores.to_csv('../Data/nba_boxscores.csv', index = False)

1982

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:12: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if sys.path[0] == '':

1982  Loaded
=================
1981
1981  Loaded
=================
1980
1980  Loaded
=================
1979
1979  Loaded
=================
1978
1978  Loaded
=================
1977
1977  Loaded
=================
1976
1976  Loaded
=================
1975
1975  Loaded
=================
1974
1974  Loaded
=================
1973
1973  Loaded
=================
1972
1972  Loaded
=================
1971
1971  Loaded
=================
1970
1970  Loaded
=================
1969
1969  Loaded
=================
1968
1968  Loaded
=================
1967
1967  Loaded
=================
1966
1966  Loaded
=================
1965
1965  Loaded
=================
1964
1964  Loaded
=================
1963
1963  Loaded
=================
1962
1962  Loaded
=================
1961
1961  Loaded
=================
1960
1960  Loaded
=================
1959
1959  Loaded
=================
1958
1958  Loaded
=================
1957
1957  Loaded
=================
1956
1956  Loaded
=================
1955
1955  Loaded
=================
1954
1954  Loaded
=================
1953
1953  Loaded
=================
1952
1952  Loaded
=================
1951
1951  Loaded
=================
1950
1950  Loaded
=================
1949
1949  Loaded
=================
1948
1948  Loaded
=================
1947
1947  Loaded
=================
1946
1946  Loaded
=================
1945
1945  Loaded
=================
1944
1944  Loaded
=================
1943
1943  Loaded
=================
1942
1942  Loaded
=================
1941
1941  Loaded
=================
1940
1940  Loaded
=================
1939
1939  Loaded
=================
1938
1938  Loaded
=================
1937
1937  Loaded
=================
1936
1936  Loaded
=================
1935
1935  Loaded
=================
1934
1934  Loaded
=================
1933
1933  Loaded
=================
1932
1932  Loaded
=================
1931
1931  Loaded
=================
1930
1930  Loaded
=================
1929
1929  Loaded
=================
1928
1928  Loaded
=================
1927
1927  Loaded
=================
1926
1926  Loaded
=================
1925
1925  Loaded
=================
1924
1924  Loaded
=================
1923
1923  Loaded
=================
1922
1922  Loaded
=================
1921
1921  Loaded
=================
1920
1920  Loaded
=================
1919
1919  Loaded
=================
1918
1918  Loaded
=================
1917
1917  Loaded
=================
1916
1916  Loaded
=================
1915
1915  Loaded
=================
1914
1914  Loaded
=================
1913
1913  Loaded
=================
1912
1912  Loaded
=================
1911
1911  Loaded
=================
1910
1910  Loaded
=================
1909
1909  Loaded
=================
1908
1908  Loaded
=================
1907
1907  Loaded
=================
1906
1906  Loaded
=================
1905
1905  Loaded
=================
1904
1904  Loaded
=================
1903
1903  Loaded
=================
1902
1902  Loaded
=================
1901
1901  Loaded
=================

In [11]:
basic_boxscores.head()

,0,0.1,0.1.1,1,1.1,1.1.1,10,10.1,10.1.1,2,2.1,2.1.1,3,3.1,3.1.1,4,4.1,4.1.1,5,5.1,5.1.1,6,6.1,6.1.1,7,7.1,7.1.1,8,8.1,8.1.1,9,9.1,9.1.1,season,0,1,2,3,4,5,6,7,8,9,10
0,201810160BOS,NaN,NaN,Philadelphia,NaN,NaN,PHI,NaN,NaN,PHI,NaN,NaN,87.0,NaN,NaN,Boston,NaN,NaN,BOS,NaN,NaN,105.0,NaN,NaN,Boston,NaN,NaN,BOS,NaN,NaN,Philadelphia,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201810160GSW,NaN,NaN,Oklahoma City,NaN,NaN,OKC,NaN,NaN,OKC,NaN,NaN,100.0,NaN,NaN,Golden State,NaN,NaN,GSW,NaN,NaN,108.0,NaN,NaN,Golden State,NaN,NaN,GSW,NaN,NaN,Oklahoma City,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201810170CHO,NaN,NaN,Milwaukee,NaN,NaN,CHO,NaN,NaN,MIL,NaN,NaN,113.0,NaN,NaN,Charlotte,NaN,NaN,CHO,NaN,NaN,112.0,NaN,NaN,Milwaukee,NaN,NaN,MIL,NaN,NaN,Charlotte,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201810170DET,NaN,NaN,Brooklyn,NaN,NaN,BRK,NaN,NaN,BRK,NaN,NaN,100.0,NaN,NaN,Detroit,NaN,NaN,DET,NaN,NaN,103.0,NaN,NaN,Detroit,NaN,NaN,DET,NaN,NaN,Brooklyn,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201810170HOU,NaN,NaN,New Orleans,NaN,NaN,HOU,NaN,NaN,NOP,NaN,NaN,131.0,NaN,NaN,Houston,NaN,NaN,HOU,NaN,NaN,112.0,NaN,NaN,New Orleans,NaN,NaN,NOP,NaN,NaN,Houston,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Below we are just doing a snapshot of the dataset by using the `head()` and `tail()` functions to ensure we have captured the dataset date limits we defined in our previous for loop.

In [12]:
basic_boxscores.shape

(68406, 45)

In [13]:
basic_boxscores.head()

,0,0.1,0.1.1,1,1.1,1.1.1,10,10.1,10.1.1,2,2.1,2.1.1,3,3.1,3.1.1,4,4.1,4.1.1,5,5.1,5.1.1,6,6.1,6.1.1,7,7.1,7.1.1,8,8.1,8.1.1,9,9.1,9.1.1,season,0,1,2,3,4,5,6,7,8,9,10
0,201810160BOS,NaN,NaN,Philadelphia,NaN,NaN,PHI,NaN,NaN,PHI,NaN,NaN,87.0,NaN,NaN,Boston,NaN,NaN,BOS,NaN,NaN,105.0,NaN,NaN,Boston,NaN,NaN,BOS,NaN,NaN,Philadelphia,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201810160GSW,NaN,NaN,Oklahoma City,NaN,NaN,OKC,NaN,NaN,OKC,NaN,NaN,100.0,NaN,NaN,Golden State,NaN,NaN,GSW,NaN,NaN,108.0,NaN,NaN,Golden State,NaN,NaN,GSW,NaN,NaN,Oklahoma City,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201810170CHO,NaN,NaN,Milwaukee,NaN,NaN,CHO,NaN,NaN,MIL,NaN,NaN,113.0,NaN,NaN,Charlotte,NaN,NaN,CHO,NaN,NaN,112.0,NaN,NaN,Milwaukee,NaN,NaN,MIL,NaN,NaN,Charlotte,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201810170DET,NaN,NaN,Brooklyn,NaN,NaN,BRK,NaN,NaN,BRK,NaN,NaN,100.0,NaN,NaN,Detroit,NaN,NaN,DET,NaN,NaN,103.0,NaN,NaN,Detroit,NaN,NaN,DET,NaN,NaN,Brooklyn,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201810170HOU,NaN,NaN,New Orleans,NaN,NaN,HOU,NaN,NaN,NOP,NaN,NaN,131.0,NaN,NaN,Houston,NaN,NaN,HOU,NaN,NaN,112.0,NaN,NaN,New Orleans,NaN,NaN,NOP,NaN,NaN,Houston,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
basic_boxscores.tail()

,0,0.1,0.1.1,1,1.1,1.1.1,10,10.1,10.1.1,2,2.1,2.1.1,3,3.1,3.1.1,4,4.1,4.1.1,5,5.1,5.1.1,6,6.1,6.1.1,7,7.1,7.1.1,8,8.1,8.1.1,9,9.1,9.1.1,season,0,1,2,3,4,5,6,7,8,9,10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947,194704160PHW,Chicago,CHS,71,Philadelphia,PHW,84,Philadelphia,PHW,Chicago,CHS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947,194704170PHW,Chicago,CHS,74,Philadelphia,PHW,85,Philadelphia,PHW,Chicago,CHS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947,194704190CHS,Philadelphia,PHW,75,Chicago,CHS,72,Philadelphia,PHW,Chicago,CHS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947,194704200CHS,Philadelphia,PHW,73,Chicago,CHS,74,Chicago,CHS,Philadelphia,PHW
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1947,194704220PHW,Chicago,CHS,80,Philadelphia,PHW,83,Philadelphia,PHW,Chicago,CHS